services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5000"
    env_file:
      - ./user-service/.env
    environment:
      DATABASE_URL: postgresql://${USER_USER}:${USER_PASSWORD}@user-db:5432/${USER_DB}
    depends_on:
      - user-db

  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${USER_USER}
      POSTGRES_PASSWORD: ${USER_PASSWORD}
    volumes:
      - ./user-service/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  housing-service:
    build: ./housing-service
    ports:
      - "5002:5000"
    env_file:
      - ./housing-service/.env
    environment:
      DATABASE_URL: postgresql://${HOUSING_USER}:${HOUSING_PASSWORD}@housing-db:5432/${HOUSING_DB}
    depends_on:
      - housing-db

  reservation-service:
    build: ./reservation-service
    ports:
      - "5003:5000"
    env_file:
      - ./reservation-service/.env
    environment:
      DATABASE_URL: postgresql://${RESERVATION_USER}:${RESERVATION_PASSWORD}@reservation-db:5432/${RESERVATION_DB}
      USER_SERVICE_URL: http://user-service:5000
      HOUSING_SERVICE_URL: http://housing-service:5000
    depends_on:
      - reservation-db

  housing-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${HOUSING_DB}
      POSTGRES_USER: ${HOUSING_USER}
      POSTGRES_PASSWORD: ${HOUSING_PASSWORD}
    volumes:
      - housing_data:/var/lib/postgresql/data
      - ./housing-service/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  reservation-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${RESERVATION_DB}
      POSTGRES_USER: ${RESERVATION_USER}
      POSTGRES_PASSWORD: ${RESERVATION_PASSWORD}
    volumes:
      - reservation_data:/var/lib/postgresql/data
      - ./reservation-service/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  housing_data:
  reservation_data: